{% set name = "pytest-alembic" %}
{% set version = "0.10.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b00360f793333a00c5cc916b661087fdc810b811e78feecd37c12110fd012f86

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry >=0.12
  run:
    - alembic
    - dataclasses
    - pytest >=1.0
    - python >=3.6
    - sqlalchemy

test:
  imports:
    - pytest_alembic
    - pytest_alembic.plugin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/schireson/pytest-alembic
  summary: A pytest plugin for verifying alembic migrations.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - igortg
    - nicoddemus
