{% set name = "pytest-alembic" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-alembic-{{ version }}.tar.gz
  sha256: 47c1a3a08c7df1f698d1e69bcd05163eff3bc76af469a57f4982f281beae5ffa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry >=0.12
  run:
    - alembic
    - dataclasses
    - pytest >=1.0
    - python >=3.6
    - sqlalchemy

test:
  imports:
    - pytest_alembic
    - pytest_alembic.plugin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/schireson/pytest-alembic
  summary: A pytest plugin for verifying alembic migrations.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - igortg
    - nicoddemus
