{% set name = "pytest-alembic" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 96a54ec76d4704fffb433880c5a84f5c3ea5980bb3f6509d868fef40e6e9a79f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - uv-build >=0.6,<0.13
  run:
    - alembic >=1.9
    - pytest >=7.0
    - python >={{ python_min }}
    - sqlalchemy >=1.4

test:
  imports:
    - pytest_alembic
    - pytest_alembic.plugin
  commands:
    - pip check
  requires:
    # Required by sqlalchemy for testing.
    - greenlet
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/schireson/pytest-alembic
  summary: A pytest plugin for verifying alembic migrations.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - igortg
    - nicoddemus
